"""enums

Revision ID: 52b2371c5096
Revises: 5dc8d9e16412
Create Date: 2026-02-07 16:21:46.026170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52b2371c5096'
down_revision: Union[str, Sequence[str], None] = '5dc8d9e16412'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friend_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('status')
    )
    op.create_index(op.f('ix_friend_status_id'), 'friend_status', ['id'], unique=False)
    op.create_table('user_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role')
    )
    op.create_index(op.f('ix_user_role_id'), 'user_role', ['id'], unique=False)
    op.add_column('friends', sa.Column('status_id', sa.Integer(), nullable=False))
    op.create_unique_constraint('unique_friendship', 'friends', ['user_id', 'friend_id'])
    op.create_foreign_key(None, 'friends', 'friend_status', ['status_id'], ['id'])
    op.drop_column('friends', 'status')
    op.add_column('users', sa.Column('role_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'users', 'user_role', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'role_id')
    op.add_column('friends', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'friends', type_='foreignkey')
    op.drop_constraint('unique_friendship', 'friends', type_='unique')
    op.drop_column('friends', 'status_id')
    op.drop_index(op.f('ix_user_role_id'), table_name='user_role')
    op.drop_table('user_role')
    op.drop_index(op.f('ix_friend_status_id'), table_name='friend_status')
    op.drop_table('friend_status')
    # ### end Alembic commands ###
