"""remove user age field from user model

Revision ID: b5330bbd8f36
Revises: 76afd52f6a66
Create Date: 2026-03-30 21:23:10.942956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5330bbd8f36'
down_revision: Union[str, Sequence[str], None] = '76afd52f6a66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'age')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('age', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
